TYPE=VIEW
query=select `s`.`student_code` AS `student_code`,concat(`s`.`first_name`,\' \',`s`.`last_name`) AS `full_name`,`g`.`grade_name` AS `grade_name`,`c`.`class_name` AS `class_name`,`s`.`status` AS `status`,round(avg(`sc`.`score`),1) AS `avg_score`,case when avg(`sc`.`score`) >= 85 then \'A\' when avg(`sc`.`score`) >= 70 then \'B\' when avg(`sc`.`score`) >= 55 then \'C\' else \'D\' end AS `grade_letter`,`f`.`amount_due` AS `amount_due`,`f`.`amount_paid` AS `amount_paid`,`f`.`amount_due` - `f`.`amount_paid` AS `balance_due`,`f`.`payment_status` AS `payment_status` from ((((`horizon_academy`.`students` `s` join `horizon_academy`.`classes` `c` on(`s`.`class_id` = `c`.`class_id`)) join `horizon_academy`.`grades` `g` on(`c`.`grade_id` = `g`.`grade_id`)) left join `horizon_academy`.`scores` `sc` on(`s`.`student_id` = `sc`.`student_id` and `sc`.`academic_year` = 2024 and `sc`.`term` = \'Term 1\')) left join `horizon_academy`.`fees` `f` on(`s`.`student_id` = `f`.`student_id` and `f`.`academic_year` = 2024 and `f`.`term` = \'Term 1\')) group by `s`.`student_id`,`s`.`student_code`,`s`.`first_name`,`s`.`last_name`,`g`.`grade_name`,`c`.`class_name`,`s`.`status`,`f`.`amount_due`,`f`.`amount_paid`,`f`.`payment_status`
md5=c7be81c979b007dd867b5b878ea0596c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001775425246094976
create-version=2
source=SELECT\n    s.student_code,\n    CONCAT(s.first_name, \' \', s.last_name)     AS full_name,\n    g.grade_name,\n    c.class_name,\n    s.status,\n    ROUND(AVG(sc.score), 1)                    AS avg_score,\n    CASE\n        WHEN AVG(sc.score) >= 85 THEN \'A\'\n        WHEN AVG(sc.score) >= 70 THEN \'B\'\n        WHEN AVG(sc.score) >= 55 THEN \'C\'\n        ELSE \'D\'\n    END                                         AS grade_letter,\n    f.amount_due,\n    f.amount_paid,\n    (f.amount_due - f.amount_paid)             AS balance_due,\n    f.payment_status\nFROM students s\nJOIN classes  c  ON s.class_id   = c.class_id\nJOIN grades   g  ON c.grade_id   = g.grade_id\nLEFT JOIN scores sc ON s.student_id = sc.student_id AND sc.academic_year = 2024 AND sc.term = \'Term 1\'\nLEFT JOIN fees  f  ON s.student_id = f.student_id  AND f.academic_year  = 2024 AND f.term  = \'Term 1\'\nGROUP BY s.student_id, s.student_code, s.first_name, s.last_name,\n         g.grade_name, c.class_name, s.status,\n         f.amount_due, f.amount_paid, f.payment_status
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `s`.`student_code` AS `student_code`,concat(`s`.`first_name`,\' \',`s`.`last_name`) AS `full_name`,`g`.`grade_name` AS `grade_name`,`c`.`class_name` AS `class_name`,`s`.`status` AS `status`,round(avg(`sc`.`score`),1) AS `avg_score`,case when avg(`sc`.`score`) >= 85 then \'A\' when avg(`sc`.`score`) >= 70 then \'B\' when avg(`sc`.`score`) >= 55 then \'C\' else \'D\' end AS `grade_letter`,`f`.`amount_due` AS `amount_due`,`f`.`amount_paid` AS `amount_paid`,`f`.`amount_due` - `f`.`amount_paid` AS `balance_due`,`f`.`payment_status` AS `payment_status` from ((((`horizon_academy`.`students` `s` join `horizon_academy`.`classes` `c` on(`s`.`class_id` = `c`.`class_id`)) join `horizon_academy`.`grades` `g` on(`c`.`grade_id` = `g`.`grade_id`)) left join `horizon_academy`.`scores` `sc` on(`s`.`student_id` = `sc`.`student_id` and `sc`.`academic_year` = 2024 and `sc`.`term` = \'Term 1\')) left join `horizon_academy`.`fees` `f` on(`s`.`student_id` = `f`.`student_id` and `f`.`academic_year` = 2024 and `f`.`term` = \'Term 1\')) group by `s`.`student_id`,`s`.`student_code`,`s`.`first_name`,`s`.`last_name`,`g`.`grade_name`,`c`.`class_name`,`s`.`status`,`f`.`amount_due`,`f`.`amount_paid`,`f`.`payment_status`
mariadb-version=100432
